# Generated by Django 6.0.2 on 2026-03-17 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone_No',
            new_name='phone',
        ),
    ]
