# Generated by Django 6.0.2 on 2026-03-18 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
