# Generated by Django 6.0.5 on 2026-05-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='students/'),
        ),
    ]
